### PR TITLE
test: dummy PR for release with Xcode 12

### PR DESCRIPTION
**Pull request by billypchan**
# What's new in this PR?

Release framework with the change of https://github.com/wireapp/wire-ios-shared-resources/pull/94

### CODE REVIEW

**Comment by billypchan** [comment]
release patch

**Comment by zenkins** [comment]
Hello, @billypchan! Merging PR for command **release patch** for PR #**237**. Will create a **patch** release after merged.
Next version is 84.0.5.

**Comment by billypchan** [comment]
release patch

**Comment by zenkins** [comment]
Hello, @billypchan! Merging PR for command **release patch** for PR #**237**. Will create a **patch** release after merged.
Next version is 84.0.5.

**Pull request merged**
