### PR TITLE
fix: accept json in image content types SQCORE-1226

### PR DESCRIPTION
**Pull request by johnxnguyen**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQCORE-1226" title="SQCORE-1226" target="_blank">BugSQCORE-1226</a>  [iOS] Profile images can't be downloaded on staging backend
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

The iOS application is showing a 406 response error when trying to fetch profile images via `GET /assets/v3/{key}`.

### Causes

The 406 error indicates that the return content type is not one of the accepted content types in the request header. The backend has changed the return type to `application/json` due to some refactoring on the backend for federation. 

### Solutions

The solution is therefore to add `application/json` to the accepted content types.

### Testing

Test the image content types contains `application/json`

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by sb88k — APPROVED** [review]

**Review by David-Henner — APPROVED** [review]

**Comment by johnxnguyen** [comment]
The iOS 13 simulator test check appears to be broken. I've verified that tests pass with Xcode 12.4 and iOS 13.7 simulator locally, so I'll ignore the check and merge.

**Comment by johnxnguyen** [comment]
release patch

**Comment by zenkins** [comment]
Hello, @johnxnguyen! Merging PR for command **release patch** for PR #**238**. Will create a **patch** release after merged.
Next version is 84.0.6.

**Comment by billypchan** [comment]
release patch

**Pull request merged**
